apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/devopsbasics-chart
    repoURL: 'https://github.com/slmakomazi/DevOpsBasics.git'
    targetRevision: argocd
    helm:
      releaseName: devops          # 👈 1. Fix: Forces short resource names like "devops-frontend"
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devopsbasics        # 👈 2. Fix: Changes the destination deployment namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true       # 👈 3. Fix: Auto-creates the "devopsbasics" namespace for you
