apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc

spec:
  storageClassName: devops-hostpath

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}